# Generated by Django 2.0.1 on 2018-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='body_text',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
