# Generated by Django 2.0.1 on 2018-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='model_pic',
            field=models.ImageField(default='assets/img/no-img.jpg', upload_to='assets/img/'),
        ),
    ]
