# Generated by Django 2.0.1 on 2018-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_heading_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='model_pic',
            field=models.ImageField(default='blog/static/blog/assets/img/header-2.jpeg', upload_to='blog/static/blog/assets/img/'),
        ),
    ]
