# Generated by Django 2.0.1 on 2018-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalstudy',
            name='eligibility_max_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinicalstudy',
            name='eligibility_min_age',
            field=models.CharField(max_length=100),
        ),
    ]
